config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :doctors do
    resources :appointments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
  validates :date, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  validates :full_name, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments
  validates :full_name, presence: true
  validates :age, presence: true
  validates :gender, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor

  def index
    @appointments = @doctor.appointments
  end

  def show
  end

  def new
    @users = User.all - @doctor.users
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)
    else 
      render :new
    end
  end

  def destroy
    @doctor.appointments.find(params[:id]).destroy
    redirect_to doctor_appointments_path(@doctor)
  end

  def edit
  end

  private
  def appointment_params
    params.require(:appointment).permit(:date, :user_id)
  end

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to root_path
  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name)
  end
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else 
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender)
  end

  def set_user
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<h1>All Appointments</h1>

<% @appointments.each do |appointment| %>
  <%= appointment.user.full_name %>
  <br />
  <%= appointment.date %>
  <br />
<% end %>

<ul>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor) %>
</ul>

app/views/appointments/new.html.erb
<h1>Appointments</h1>

<%= form_with(model: [@doctor, @appointment], local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_field :date, pressence: true %>
  </div>
  <br />
</div>
<div class="field">
<%= f.label :user %>
<%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
</div>
<br />
  <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/appointments/show.html.erb
<h1>Add Appointment</h1>

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>

<%= form_with(model: @doctor, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/doctors/index.html.erb
<h1 class="ui center aligned icon header">
  <i class="user md icon"></i>
  Doctors
</h1>
<h2><%= @doctors.length <= 0 ? 'No Doctors' : "" %></h2>
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.full_name, doctor %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1 class="ui center aligned icon header">
  <i class="user md icon"></i>
  Add Doctor
</h1>

<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true %>
  </div>
  <br />
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>
  <br />

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.full_name %></h1>
<%= link_to 'Appointments', doctor_appointments_path(@doctor) %>
<br />
<%= link_to 'Delete Doctor', @doctor, method: :delete, class: 'ui red button' %>
<%= link_to 'Edit Doctor Info', edit_doctor_path(@doctor), class: 'ui black button' %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="ui four item menu">
    <a class="active item" <%= link_to 'Doctors', doctors_path %></a>
    <a class="item" <%= link_to 'Add Doctor', new_doctor_path %></a>
    <a class="item" <%= link_to 'Users', users_path  %></a>
    <a class="item" <%= link_to 'Add User', new_user_path %></a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsAppointments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1 class="ui center aligned icon header">
  <i class="plus square outline icon"></i>
  Users
</h1>
<ul>

  <% @users.each do |user| %>
    <li>
      <%= link_to user.full_name, user %>
    </li>
  <% end %>

</ul>

app/views/users/new.html.erb
<h1 class="ui center aligned icon header">
  <i class="plus square outline icon"></i>
  Add User
</h1>

<%= form_with(model: @user, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>

  <div class="field">
  <%= f.label :age %>
  <%= f.text_field :age, required: true %>
<br />
  <div class="field">
  <%= f.label :gender %>
  <%= f.text_field :gender, required: true %>
  <br />
  
  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/users/show.html.erb
<h1>Users</h1>

  
<h1><%= @user.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul>
  <% @user.doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
    <% end %>
</ul>
<ul>
    <% @user.appointments.each do |appointment| %>
      <%= link_to appointment.date, appointment %>
  <% end %>
</ul>
<br />
<%= link_to 'Delete User', @user, method: :delete, class: 'ui red button' %>